[project]
name = "uiautodev-utest"
version = "0.9.1"
description = "Mobile UI Automation, include UI hierarchy inspector, script recorder"
authors = [
    { name = "codeskyblue", email = "codeskyblue@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"

# 项目依赖
dependencies = [
    "click>=8.1.7",
    "pygments>=2",
    "fastapi==0.115.12",
    "pydantic>=2.6",
    "wdapy>0.2.2,<1",
    "websockets>=10.4",
    "pillow",
    "construct",
    "lxml",
    "httpx",
    "uvicorn>=0.33.0",
    "whichcraft==0.6.1",
    "setuptools==64",
    "packaging>=20.3,<21",
    "rich",
    "python-multipart>=0.0.18",
    "adbutils==0.16.2",
    "utest-uiautomator2==2.16.17.dev42",
    "filelock",
    "logzero",
    "six",
    "cached_property",
    "progress",
    "twine>=6.0.1",
]

# 可选依赖（开发依赖）
[project.optional-dependencies]
dev = [
    "pytest>=8.0.1",
    "isort>=5.13.2",
    "pytest-cov>=4.1.0",
]

[project.scripts]
"uiauto.dev" = "uiautodev.__main__:main"
"uiautodev" = "uiautodev.__main__:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["uiautodev*"]

[tool.setuptools.package-data]
uiautodev = ["binaries/*"]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[[tool.uv.index]]
url = "https://mirrors.tencent.com/repository/pypi/tencent_pypi/simple"
